version: "3"
services:
  app:
    tty: true
    image: johannesk13/ai-repo:oemer
    container_name: oemer
    restart: always
    volumes:
       - ./input:/input
       - ./output:/output
       - ./processed:/processed
    entrypoint: sh -c "/watch-incoming.sh"
